let total_counter=document.querySelector(".total_counter");const price_total=document.querySelector(".price-total");window.addEventListener("load",function(){let e=this.document.querySelector(".loader");e.classList+=" hidden"});const intro=document.querySelector(".intro"),text=document.querySelectorAll(".logo"),img_intro=document.querySelector(".img-intro");window.addEventListener("load",()=>{setTimeout(()=>{text.forEach((e,t)=>{setTimeout(()=>{e.classList.add("active")},(t+1)*400)})}),setTimeout(()=>{text.forEach(e=>{setTimeout(()=>{e.classList.remove("active"),e.classList.add("fade"),img_intro.classList.add("fade")},1500)})},3e3),this.setTimeout(()=>{intro.style.top="-100vh"},4e3)});const tab_menu=document.querySelector(".tab-menu").children,list_ul=document.querySelector(".list-ul").children;for(let i=0;i<list_ul.length;i++)list_ul[i].style.display="none","cake"==list_ul[i].getAttribute("data-category")&&(list_ul[i].style.display="block");for(let i=0;i<tab_menu.length;i++)tab_menu[i].addEventListener("click",function(){for(let e=0;e<tab_menu.length;e++)tab_menu[e].children[0].classList.remove("active");tab_menu[i].children[0].classList.add("active");let t=tab_menu[i].getAttribute("data-filter");for(let l=0;l<list_ul.length;l++)list_ul[l].style.display="none";for(let a=0;a<list_ul.length;a++)t==list_ul[a].getAttribute("data-category")&&(list_ul[a].style.display="block")});const shop_cart=document.querySelector(".shop"),shop_items=document.querySelector(".shopping-items");shop_cart.addEventListener("click",()=>{shop_items.classList.toggle("active")});let cartitems=JSON.parse(localStorage.getItem("cart_items"))||[];document.addEventListener("DOMContentLoaded",loadData());const btn_list=document.querySelectorAll(".btn-list");function savetolocal(){localStorage.setItem("cart_items",JSON.stringify(cartitems))}function AddItemToTheDom(e){shop_items.insertAdjacentHTML("afterbegin",`      
    <div class="shopping-oneitem">
  <div class="detail-shop">
  <input type="hidden" id="product-id" value=${e.id}>
    <img src=${e.img_pro} alt="" class="shopping-img" />
    <div class="name-item"><span class="name">${e.title_pro}</span></div>
  </div>

  <div class="item-control">
    <span class="icon-plus icon-sh"
      ><i class="fa-solid fa-plus fs-5 " action="increase"></i
    ></span>
    <span class="number-item">${e.quantity}</span>
    <span class="icon-minus icon-sh "
      ><i class="fa-solid fa-minus fs-5 "></i
    ></span>
    <span class="number-price">${e.price_pro} تومان</span>

    <span class="icon-trash" ><i class="fa-solid fa-trash-can icon-sh fs-5 "></i></span>
  </div>
</div>
`)}function CalculateTotal(){let e=0;cartitems.forEach(t=>{e+=t.quantity*t.price_pro}),price_total.innerText=e+".000 تومان ",total_counter.innerText=cartitems.length}function increaseitem(e,t){e.querySelector(".icon-plus").addEventListener("click",()=>{cartitems.forEach(l=>{l.id===t.id&&(e.querySelector(".number-item").innerText=++l.quantity,CalculateTotal(),savetolocal())})})}function decreaseitem(e,t){e.querySelector(".icon-minus").addEventListener("click",()=>{cartitems.forEach(l=>{if(l.id===t.id){if(e.querySelector(".number-item").innerText=--l.quantity,0===l.quantity){e.style.display="none";for(let a=0;a<cartitems.length;a++)cartitems[a]===l&&cartitems.splice(a,1)}CalculateTotal(),savetolocal()}})})}function delitem(e,t){e.querySelector(".icon-trash").addEventListener("click",()=>{let t=e.querySelector("#product-id").value;e.style.display="none";for(let l=0;l<cartitems.length;l++)cartitems[l].id===t&&cartitems.splice(l,1);CalculateTotal(),savetolocal()})}function loadData(){cartitems.length>0&&(cartitems.forEach(e=>{AddItemToTheDom(e);document.querySelectorAll(".shopping-oneitem").forEach(t=>{t.querySelector("#product-id").value===e.id&&(increaseitem(t,e),decreaseitem(t,e),delitem(t,e))})}),CalculateTotal(),savetolocal())}function cleardata(){localStorage.clear(),cartitems=[],document.querySelectorAll(".shopping-oneitem").forEach(e=>{e.remove()}),CalculateTotal()}btn_list.forEach(e=>{e.addEventListener("click",()=>{let t=e.parentElement,l={id:t.querySelector("input").value,img_pro:t.querySelector(".img-list").src,title_pro:t.querySelector(".title").innerText,price_pro:t.querySelector(".price").innerText,quantity:1};if(cartitems.filter(e=>e.id===l.id).length>0){alert(" این محصول در سبد خرید هست.");return}AddItemToTheDom(l);document.querySelectorAll(".shopping-oneitem").forEach(e=>{e.querySelector("#product-id").value===l.id&&(increaseitem(e,l),decreaseitem(e,l),delitem(e,l))}),cartitems.push(l),savetolocal(),CalculateTotal()})}),document.querySelector(".shopping-btn").addEventListener("click",()=>{cleardata()});